#!/usr/bin/env bash

set -euo pipefail

NAME=${1:-}
PID=${2:-}

if [[ -z "$NAME" ]] || [[  -z "$PID" ]];then
   echo "$0 <indicator name> <PID>"
   exit 1
fi

sind "$NAME" "#0ff"

set +e

tail "--pid=$PID" -f /dev/null  # Wait for the process to end

RES=$?

# Note that we actually cannot get a useful return code here!
sind "$NAME" "#0f0"

# Great place for notify-send/play/gotify

exit $RES
