#!/usr/bin/env bash

set -euo pipefail

NAME=${1:-}

FILE=/tmp/indicators.json

if [ ! -f "$FILE" ];then
    echo '{}' > $FILE
else
    flock "$FILE" -c "bash -c '
      set -euo pipefail
      new_value=\`jq <\"$FILE\" \"del(.$NAME)\"\`;

      echo \"{}\" >\"$FILE\"
'"
fi
